name: vagrant-up

on: [push]

jobs:
  vagrant-up:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install package
      run: sudo apt update && sudo apt-get -y install virtualbox wget curl
    - name: Download & install vagrant
      run: wget -O https://releases.hashicorp.com/vagrant/2.2.16/vagrant_2.2.16_x86_64.deb && apt -y install .vagrant*

    - name: Cache Vagrant boxes
      uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
        restore-keys: |
          ${{ runner.os }}-vagrant-

    - name: Run vagrant up
      run: vagrant up
      working-directory: ./vagrant/esp8266-micropython-vagrant

    - name: ssh into box after boot
      run: vagrant ssh -c "cd /vagrant/micropython/ports/esp8266 && make"
